# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: rust-toolchain
        # You may pin to the exact commit or the version.
        # uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          # Target triple to install for this toolchain
          target: x86_64-unknown-linux-gnu 
          # Set installed toolchain as default
          default: true
          # Set installed toolchain as an override for a directory
          override: true
          # Name of the group of components to be installed for a new toolchain
          
          # Comma-separated list of components to be additionally installed for a new toolchain
          components: clippy, rustfmt          
      - name: clippy
        # You may pin to the exact commit or the version.
        # uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        uses: actions-rs/cargo@v1.0.1
        with:
          # Cargo command to run (ex. `check` or `build`)
          command: clippy
          args: -D warnings
          # Toolchain to use (without the `+` sign, ex. `nightly`)
          toolchain: stable
      - name: fmt
        # You may pin to the exact commit or the version.
        # uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        uses: actions-rs/cargo@v1.0.1
        with:
          # Cargo command to run (ex. `check` or `build`)
          command: fmt
          args: --check
          # Toolchain to use (without the `+` sign, ex. `nightly`)
          toolchain: stable
      - name: test
        # You may pin to the exact commit or the version.
        # uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        uses: actions-rs/cargo@v1.0.1
        with:
          # Cargo command to run (ex. `check` or `build`)
          command: test
          # Toolchain to use (without the `+` sign, ex. `nightly`)
          toolchain: stable
